<?php

$lang = array(
    // Boutons
    "Btn_Annuler" => "Annuler",
    "Btn_Modifier" => "Modifier",
    "Btn_Enregistrer" => "Enregistrer",
    "Btn_Supprimer" => "Supprimer",
    "Btn_MaJ" => "Mettre à jour",
    "Btn_Connecter" => "Se connecter",
    "Btn_NvBat" => "Nouveau bâtiment",
    "Btn_ReinitialiserFiltre" => "Réinitialiser filtre",
    "Btn_Uploader" => "Uploader",
    "Btn_Deconnexion" => "Se déconnecter",
    "Btn_FDS" => "FDS",
    "Btn_Modifier_Mdp" => "Modifier le mot de passe",
    "Btn_Nv_Role" => "Nouveau rôle",
    "Btn_Nv_Emp" => "Nouvel(le) employé(e)",
    "Btn_Vue_Categories" => "vue categories",
    "Btn_Nv_Categorie" => "Nouvelle catégorie",
    "Btn_Nv_Personne" => "Nouvelle personne",
    "Btn_Nv_Icpe_Max" => "Nouveau ICPE max",
    "Btn_Upload" => "Upload",
    "Btn_Nv_Icpe_Acceptee" => "Nouveau ICPE acceptée",
    "Btn_Nv_Compteur" => "Nouveau compteur",
    "Btn_Encodage" => "Encodage ICPE",
    "Btn_Nv_Locataire" => "Nouveau locataire",
    "Btn_Nv_Article" => "Nouvel article",
    "Btn_Nv_Poteau" => "Nouveau poteau",
    "Btn_Nv_Vanne" => "Nouvelle vanne",
    "Btn_Nv_Separateur" => "Nouveau séparateur",
    "Btn_Nv_Reserve" => "Nouvelle réserve",
    "Btn_Nv_Reserve_Na" => "Nouvelle réserve n/a",
    //////////////////////////////////////////////////////////////////////////////////////////////////////// 
    // Page de connexion
    "Lbl_LoginTitre" => "Connexion Espace Client",
    "Tbx_Identifiant" => "Identifiant",
    "Tbx_Mdp" => "Mot de passe",
    "Chkbx_ConditionUtilisation" => "J’accepte les conditions générales d’utilisation",
    "Lnk_MdpOublie" => "Mot de passe oublié ?",

    //////////////////////////////////////////////////////////////////////////////////////////////////////// 
    // Menu latérale page home
    "Sdbr_Lbl_Admin" => "Administration",
    "Sdbr_Btn_MonCompte" => "Mon compte",
    "Sdbr_Btn_Utilisateurs" => "Gestion utilisateurs",

    //////////////////////////////////////////////////////////////////////////////////////////////////////// 
    // Menu latérale page base
    "Sdbr_Btn_EtatMatStk" => "Etats des matières stockées",
    "Sdbr_Btn_RessourceEau" => "Ressource en eau",
    "Sdbr_Btn_Pers" => "Personne à prévenir",
    "Sdbr_Btn_Doc" => "Documentation",
    "Sdbr_Btn_Bat" => "Bâtiments",
    "Sdbr_Btn_Param" => "Paramétrages",

    //////////////////////////////////////////////////////////////////////////////////////////////////////// 
    // Menu entête
    
    //////////////////////////////////////////////////////////////////////////////////////////////////////// 
    //Page home
    "Lbl_HomeTitre" => "Liste batiments",
    "Lbl_Activite" => "Activité",
    "Slctbx_Activites" => "Toutes les activités",
    "Lbl_Recherche" => "Recherche",
    "Tbl_Head_NomBat" => "Noms bâtiments",
    "Tbl_Head_Activite" => "Activités",
    "Tbl_Head_Adresse" => "Adresse",
    "Tbl_Head_CP" => "CP",
    "Tbl_Head_Ville" => "Ville",

    //////////////////////////////////////////////////////////////////////////////////////////////////////// 
    // Page home - modal - plan
    "Mdl_PlanTitre" => "Plan",

    //////////////////////////////////////////////////////////////////////////////////////////////////////// 
    // Page home - modal - ajouter / modifier batiment
    "Mdl_NvBat_Title" => "Nouveau bâtiment",
    "Mdl_MdfBat_Title" => "Modifier le bâtiment",
    "Mdl_NvBat_MaisonMere" => "Maison mère ",
    "Mdl_NvBat_MaisonMere_Existe" => "Maison mère existant",
    "Mdl_NvBat_MaisonMere_Nv" => "Nouvelle maison mère",
    "Mdl_NvBat_Slct_MaisonMere" => "Sélectionnez une maison mère",
    "Mdl_NvBat_NvMm_Nom" => "Nom",
    "Mdl_NvBat_NvMm_Email" => "Email",
    "Mdl_NvBat_NvMm_Tel" => "Téléphone",
    "Mdl_NvBat_NvMm_Adresse" => "Adresse",
    "Mdl_NvBat_NvMm_CP" => "Code postale",
    "Mdl_NvBat_NvMm_Pays" => "Pays",
    "Mdl_Bat_Nom" => "Nom du bâtiment",
    "Mdl_Bat_Activite" => "Activité",
    "Mdl_Bat_Adresse" => "Adresse",
    "Mdl_Bat_CP" => "Code postale",
    "Mdl_Bat_Ville" => "Ville",

    //////////////////////////////////////////////////////////////////////////////////////////////////////// 
    // Page mon compte
    "Lbl_Mcompte_Titre" => "Mon compte utilisateur",
    "Lbl_Compte_Util_Titre" => "Compte utilisateur",
    "Lbl_Mc_Util" => "Nom utilisateur",
    "Lbl_Mc_Email" => "Email utilisateur",
    "Lbl_Mc_Role" => "Enregistrer en tant",
    "Lbl_Donne_Perso" => "Donnee personnelle",
    "Lbl_Nom_Prenom" => "Nom et prénom",
    "Lbl_Nom" => "Nom",
    "Lbl_Prenom" => "Prénom",
    "Lbl_Fonction" => "Fonction",
    "Lbl_Email" => "Email",
    "Lbl_Courielle" => "Courielle",
    "Lbl_Tel_Fixe" => "Téléphone (fixe)",
    "Lbl_Tel" => "Télephone",
    "Lbl_Tel_Min" => "Tel",
    "Lbl_Tel2" => "Télephone 2",
    "Lbl_Adresse" => "Adresse",
    "Lbl_Localisation" => "Localisation",
    "Lbl_Role_Titre" => "Parametrer les roles",
    "Lbl_Supp_Role_Titre" => "Supprimer un role",
    "Lbl_Supp_Role_Sur" => "Voulez-vous supprimer le rôle ci-dessous :",
    "Lbl_Modif_Role_Titre" => "Modifier un role",
    "Lbl_Nv_Role_Titre" => "Nouveau role",
    "Lbl_Modif_Util_Titre" => "Modifier utilisateur",
    "Lbl_Modif_Mdp_Titre" => "Changer le mot de passe",
    "Lbl_Modif_Mdp_Ancient" => "Ancient mot de passe",
    "Lbl_Modif_Mdp_Nv" => "Nouveau mot de passe",
    "Lbl_Modif_Mdp_ConfirmeNv" => "Confirmer le nouveau mot de passe",
    "Lbl_Modif_Emp_Titre" => "Modifier employe(e)",

    //////////////////////////////////////////////////////////////////////////////////////////////////////// 
    // Page gere utilisateurs
    "Lbl_List_Utils_Titre" => "Liste utilisateurs",
    "Lbl_Acces_Emp_Titre" => "Acces employe(e)",
    "Lbl_Nv_Emp_Titre" => "Ajout un employe(e)",

    //////////////////////////////////////////////////////////////////////////////////////////////////////// 
    // Page matiere ICPE
    "Alert_Txt_NoProbleme" => "Aucun problème à signaler",
    "Alert_Txt_Warning" => "Attention le sock maximun est bientôt atteint pour code ICPE",
    "Alert_Txt_Danger" => "Le stock maximun est atteint pour le code ICPE",
    "Alert_Txt_Danger_Article" => "Un ou plusieurs article ne figure pas sur la fiche article",
    "Alert_Txt_Danger_Icpe_No_Autorise" => "Un ou plusieurs ICPE non autorisé dans une zone",
    "Lbl_Icpe_Titre" => "Etats de matieres stockees",
    "Lbl_Recherche_Icpe" => "Rechercher par icpe",
    "Lbl_Tous" => "Tous",
    "Lbl_Alerte" => "Alerte",
    "Lbl_DateImport" => "Date d'import",
    "Tbl_Head_Nom" => "Nom",
    "Tbl_Head_Action" => "Action",
    "Tbl_Head_Rubrique_Icpe" => "Rubrique ICPE",
    "Tbl_Head_Stock_Max" => "Stock max",
    "Tbl_Head_Stock_Total" => "Stock total présent",
    "Tbl_Head_Reglementation_Icpe" => "Règlementation ICPE",
    "Tbl_Head_Code_Icpe" => "Code ICPE",
    "Tbl_Head_Designation" => "Designation",
    "Tbl_Head_Plan_Stockage" => "Plan de stockage",
    "Tbl_Head_PMD" => "PMD",
    "Tbl_Head_Qte" => "Quantité",
    "Tbl_Head_Qte_Min" => "Qte",
    "Tbl_Head_Localisation" => "Localisation",
    "Tbl_Head_Mention_danger" => "Mention du danger",
    "Tbl_Head_Unite" => "Unité",
    "Tbl_Head_Emplacement" => "Emplacement",
    "Tbl_Head_Allee" => "Allée",
    "Tbl_Head_Rack" => "Rack",
    "Tbl_Head_Details_Article" => "Details article",
    "Tbl_Head_FDS" => "FDS",
    "Tbl_Head_Prevention" => "Prévention",
    "Tbl_Head_Description" => "Description",
    "Tbl_Head_Description_Danger" => "Description mention danger",
    "Tbl_Head_Description_Prevention" => "Description prévention",
    "Tbl_Head_Icpe_max" => "ICPE max",
    "Tbl_Head_Stock_present" => "Stock présent",
    "Mdl_Titre_Detail_Article" => "Details article",

    //////////////////////////////////////////////////////////////////////////////////////////////////////// 
    // Page personne à prévenir
    "Tbl_Head_Fonction_Activite" => "Fonction / Activité",
    "Tbl_Head_Contact" => "Contact",
    "Tbl_Head_Adresse_Horaire" => "Adresse / Horaires",
    "Tbl_Head_Fixe" => "Fixe",
    "Tbl_Head_Port" => "Port.",
    "Tbl_Head_Portable" => "Portable",

    ////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Page documentation
    "Lbl_Telecharge_Fichier" => "Télécharger le fichier ",

    //////////////////////////////////////////////////////////////////////////////////////////////////////// 
    // Page paramétrage
    "Lbl_Param_Icpe_max" => "Parametrage icpe max",
    "Tbl_Head_Icpe_Min" => "Icpe",
    "Tbl_Head_Max" => "Max",
    "Tbl_Head_Unite_Up" => "Unite",
    "Lbl_Pas_Icpe_Max" => "Pas de ICPE max enregistré",
    "Lbl_Param_Icpe_Accepte" => "Parametrage icpe accepte",
    "Tbl_Head_Allee_Up" => "Allee",
    "Tbl_Head_Icpe_Accepte" => "Icpe accepte",
    "Lbl_Pas_Icpe_Accepte" => "Pas de code ICPE accepté enregistré",
    "Lbl_Param_Cat_Personne" => "Parametrage categorie personne a prevenir",
    "Tbl_Head_Num" => "Num",
    "Tbl_Head_Libelle" => "Libelle",
    "Lbl_Pas_Cat_Perso" => "Aucune catégorie de personne enregistré",
    "Lbl_Param_Icpe_Cat" => "Parametrage code icpe et categorie",
    "Tbl_Head_Num_Art" => "Num article",
    "Tbl_Head_Num_Art_Min" => "Num art",
    "Tbl_Head_Descriptif" => "Descriptif",
    "Tbl_Head_Categorie" => "Categorie",
    "Lbl_Pas_Encodage_Icpe" => "Pas d'encodage ICPE enregistrer",
    "Lbl_Param_Locataire" => "Parametrage locataires",
    "Tbl_Head_Email" => "Email",
    "Lbl_Pas_Client" => "Aucun client enregistré",
    "Lbl_Param_Stock_Journalier" => "Parametrage du stock journalier",
    "Tbl_Head_Dernier_Up" => "Derniere upload",
    "Lbl_Pas_Upload_Init" => "Aucun upload initié à ce jour",
    "Lbl_Param_Article" => "Parametrage article",
    "Tbl_Head_Libelle_Art" => "Libelle art",
    "Tbl_Head_Fournisseur" => "Fournisseur",
    "Tbl_Head_Etats" => "Etats",
    "Tbl_Head_Etat" => "Etat",
    "Tbl_Head_Conditionnement" => "Conditionnement",
    "Tbl_Head_Point_Eclaire" => "Point eclaire",
    "Tbl_Head_Point_Eclaire_2" => "Point éclaire",
    "Tbl_Head_Fumee_Decomp" => "Fumee decomposition",
    "Tbl_Head_Fumee_Decomp_2" => "Fumée décomposition",
    "Lbl_Pas_Article" => "Aucun article enregistré",
    "Mdl_Encodage_Icpe_Titre" => "Encodage code icpe",
    "Lbl_Num_Art" => "Numéro article",
    "Lbl_Categorie" => "Catégorie",
    "Slct_Categorie" => "Veuillez choisir une catégorie",
    "Mdl_Nv_Icpe_Max" => "Nouveau icpe max",
    "Lbl_Icpe" => "ICPE",
    "Lbl_Selectionnez" => "Selectionnez",
    "Lbl_Regime" => "Regime",
    "Lbl_Code_Cat" => "Code de Catégorie",
    "Lbl_Confirm_Supp" => "Confirmation de suppressin",
    "Lbl_Supp_Question" => "Êtes-vous sûr de vouloir supprimer cet élément ?",
    "Lbl_Nv_Icpe_Accept" => "Nouveau ICPE acceptee",
    "Lbl_Avc_Allee" => "Avec Allée",
    "Lbl_Avc_Rack" => "Avec Rack",
    "Lbl_Icpe_Acceptee" => "ICPE acceptée",
    "Lbl_All_Icpe" => "Toutes les ICPE",
    "Slct_Opt_Batiment" => "Bâtiment",
    "Slct_Opt_Localisation" => "Localisation",
    "Lbl_Icpe_Acc_Bat" => "ICPE acceptée par bâtiment",
    "Mdl_Titre_Nv_Locataire" => "Nouveau locataire",
    "Lbl_Tel_Fixe" => "Tél. fixe",
    "Lbl_Tel_Port" => "Tél. portable",
    "Mdl_Titre_Nv_Article" => "Nouvel article",
    "Lbl_Propos_classement" => "Proposition de classement",
    "Mdl_Titre_Nv_Import" => "Import",
    "Lbl_Locataire_Existe" => "Locataire enregistré",
    "Lbl_Locataire_Nv" => "Nouveau locataire",
    "Slct_Lbl_Locataire" => "Sélectionnez un locataire",
    "Lbl_Zone_Stockage" => "Zone de stockage",
    "Slct_Lbl_Zone_Stockage" => "Sélectionnez une zone",
    "Lbl_Nv_Emplacement" => "Nouvel emplacement",
    "Lbl_Emplacement_Existe" => "Emplace enregistré",
    "Slct_Lbl_Emplacement" => "Sélectionner un emplacement",
    "Lbl_Nbr_Palette" => "Nombre de palette",
    "Mdl_Titre_Up_Icpe_Max" => "Upload ICPE max",
    "Mdl_Titre_Up_Icpe_Accept" => "Upload ICPE accepter",
    "Mdl_Titre_Up_Encodage" => "Upload code ICPE et categorie",
    "Mdl_Titre_Up_Liste_Locataire" => "Upload liste locataire",
    "Mdl_Titre_Up_stock" => "Upload du stock",
    "Lbl_Fichier_Csv" => "Le fichier pris en charge doit être au format (.csv)",
    "Lbl_Fichier_Csv_Placement" => "Les données du fichier (.csv) doivent êtres placée dans cette ordre",
    
    //////////////////////////////////////////////////////////////////////////////////////////////////////// 
    // Page ressource eau
    "Lbl_Eau_Titre" => "Ressource en eau",
    "Tbl_Head_Compteur_Eau" => "Compteur eau",
    "Tbl_Head_Poteau_Incendie" => "Poteau incendie",
    "Tbl_Head_Reserve_Eau" => "Réserve d'eau",
    "Tbl_Head_Reserve_Eau_Artificielle" => "Réserve d'eau naturelle ou artificielle",
    "Tbl_Head_Separateur_Hydro" => "Séparateur d'hydrocarbures",
    "Tbl_Head_Vanne" => "Vanne",
    "Tbl_Head_Point" => "Point",
    "Tbl_Head_Debit" => "Débit",
    "Tbl_Head_Pression" => "Pression",
    "Tbl_Head_Info_Comp" => "Info Comp.",
    "Tbl_Head_Gueul_Bee" => "Max (à gueule-bée)",
    "Tbl_Head_bar" => "bar",
    "Tbl_Head_Simultane" => "Simultané",
    "Tbl_Head_Statique" => "Statique",
    "Tbl_Head_Diametre" => "Diamètre nominal",
    "Tbl_Head_Nbre_prise" => "Nombre prise",
    "Tbl_Head_Volume" => "Volume",
    "Tbl_Head_Capacite" => "Capacité",
    "Tbl_Head_Type" => "Type",
    "Tbl_Head_Caracteristique" => "Caractéristiques",
    "Tbl_Head_Bassin_Retention_Ep" => "Bassin de rétention EP",
    "Tbl_Head_Reserve_incendie" => "Réserve incendie",
    "Tbl_Head_Poteau_Incendie" => "Poteau incendie N°02",
    "Tbl_Head_Poteau_Incendie_Prive" => "Poteau incendie privé N°03",
);